apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: inventory-system
spec:
  parameters:
    userAssignedIdentityID: "PLACEHOLDER_PRD"  # Will be set when PRD addon is enabled
    keyvaultName: "kv-appg5-prd"
