apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: inventory-system
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "931819cb-d0f0-4efa-8421-239a2d6c4696"  # Will be replaced per environment
    keyvaultName: "kv-appg5-dev"  # Will be replaced per environment
    cloudName: ""
    objects: |
      array:
        - |
          objectName: SqlConnectionString
          objectType: secret
          objectVersion: ""
    tenantId: "902d0f18-7f05-46f8-b697-f282d4263bed"
  secretObjects:
  - secretName: sql-connection-secret
    type: Opaque
    data:
    - objectName: SqlConnectionString
      key: ConnectionStrings__SqlConnection
